sudo: required
services:
    - docker
env:
    global:
    - SHA=$(git rev-parse HEAD)
before_install:
    - docker build -t mihailiucalin_scrapper/distrib:latest -f ./distrib_scrapper/Dockerfile ./distrib_scrapper
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push mihailiucalin/distrib_scrapper:latest
script:
    - docker run mihailiucalin/distrib_scrapper:latest